### ISSUE TITLE
What's the license of this project?

### ISSUE THREAD

**Issue by zzxwill** [broadinstitute/docker-terraform#19]
This docker image is cool! It's better than the official one https://hub.docker.com/r/hashicorp/terraform which cannot process JSON configuration files.

I'd like to fork this project, modify some of the source code and build the image.

**Comment by zzxwill** [comment]
@coreone @hjfbynara @RLuckom @lukwam @jack-r-warren Could anyone help clarify the licensing? Thanks.

**Comment by jack-r-warren** [comment]
Sorry I didn't see this earlier--I'm not at Broad right now, had to finish school. Might be of more help when I'm back there in a bit if this isn't resolved by then.

Good catch on there not being a license here. I'm not quite sure who would make the call on adding one, asking @hjfbynara would be my first stop.

**Comment by jack-r-warren** [comment]
^ @zzxwill better late than never, had to sort out permissions on this repo. Let me know if the above PR doesn't address this.

**Comment by zzxwill** [comment]
Appreciated:)
